export const VIEW_HEADER='VIEW_HEADER'
export const VIEW_NAV='VIEW_NAV'
export const VIEW_FOOTER='VIEW_FOOTER'
export const CHECK_USER='CHECK_USER'
export const SHOPPING='SHOPPING'
export const DEL_SHOPPING='DEL_SHOPPING'